### ISSUE TITLE
有点丑

### ISSUE THREAD

**Issue by cmwode** [maplesugarr/hexo-next-friends-tag#1]
{% linkgrid style1 false %}
枫糖 | https://blog.maplesugar.space | https://cdn.jsdelivr.net/gh/maplesugarr/blog-assets@master/imgs/maple-leaf-avatar.jpg
{% endlinkgrid %}

效果有点丑:
![image](https://user-images.githubusercontent.com/42599739/83512801-50f5ea80-a503-11ea-94a1-b323af157edb.png)

只需要安装插件，新建友链页面就行了吗？
还需要其他的东西吗?

**Comment by maplesugarr** [comment]
插件装错了吧？我的确是参考npm install theme-next/hexo-next-tag这个插件的。
我的插件是下面这个
`npm install hexo-next-friends-tag --save`

**Comment by maplesugarr** [comment]
可能是标签冲突，我改一下标签好了。
